# Generated by Django 5.2.7 on 2025-10-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latin', models.CharField(blank=True, default='', max_length=200)),
                ('popular', models.BooleanField(default=False)),
                ('sun', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('water', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('image_thumb_url', models.URLField(blank=True, default='')),
                ('image_hero_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('traits', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['popular'], name='plants_plan_popular_51d8ee_idx'), models.Index(fields=['name'], name='plants_plan_name_abe05c_idx'), models.Index(fields=['latin'], name='plants_plan_latin_bb1bc7_idx')],
            },
        ),
    ]
