# Generated by Django 5.2.7 on 2025-10-14 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('traits', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name', 'latin']},
        ),
        migrations.RemoveIndex(
            model_name='plant',
            name='plants_plan_popular_51d8ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='plant',
            name='plants_plan_name_abe05c_idx',
        ),
        migrations.RemoveIndex(
            model_name='plant',
            name='plants_plan_latin_bb1bc7_idx',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image_hero_url',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image_thumb_url',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='traits',
        ),
        migrations.AddField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='latin',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sun',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AddField(
            model_name='plantprofile',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='plants.plant'),
        ),
    ]
