# Generated by Django 5.2.7 on 2025-10-14 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plantprofile_alter_plant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plant',
            name='image_hero_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plant',
            name='image_thumb_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plant',
            name='traits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.DeleteModel(
            name='PlantProfile',
        ),
    ]
