# Generated by Django 5.2.7 on 2025-10-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plant_options_remove_plant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image_hero_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image_thumb_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
