# Generated by Django 4.2 on 2026-01-16 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_instances', '0003_backfill_qr_codes'),
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingdevice',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_devices', to='plant_instances.plantinstance'),
        ),
    ]
