# Generated by Django 4.2 on 2026-03-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_alter_readingdevice_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingdevice',
            name='moisture_alert_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingdevice',
            name='moisture_alert_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingdevice',
            name='moisture_alert_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
