# Generated by Django 4.2 on 2026-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_readingdevice_moisture_alert_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingdevice',
            name='automatic_pump_launch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingdevice',
            name='last_pump_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingdevice',
            name='pump_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingdevice',
            name='pump_threshold_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingdevice',
            name='send_email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingdevice',
            name='send_push_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='readingdevice',
            name='interval_hours',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
