# Generated by Django 4.2 on 2026-04-27 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readings', '0004_readingdevice_automatic_pump_launch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingdevice',
            name='last_pump_run_source',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='readingdevice',
            name='pump_cooldown_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.CreateModel(
            name='PumpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('moisture_at_request', models.FloatField(blank=True, null=True)),
                ('threshold_at_request', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pump_tasks', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_tasks', to='readings.readingdevice')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.AddIndex(
            model_name='pumptask',
            index=models.Index(fields=['device', 'status', 'source'], name='readings_pu_device__50d2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='pumptask',
            index=models.Index(fields=['expires_at'], name='readings_pu_expires_8461d8_idx'),
        ),
    ]
