# Generated by Django 4.2 on 2026-04-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_readingdevice_last_pump_run_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingdevice',
            name='send_email_watering_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingdevice',
            name='send_push_watering_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
