# Generated by Django 4.2 on 2025-12-22 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant_definitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantTraitDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='plantdefinition',
            options={'ordering': ['name', 'latin']},
        ),
        migrations.RemoveField(
            model_name='plantdefinition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plantdefinition',
            name='image_hero_url',
        ),
        migrations.RemoveField(
            model_name='plantdefinition',
            name='image_thumb_url',
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='external_id',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='fertilize_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='fertilize_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='image_hero',
            field=models.ImageField(blank=True, null=True, upload_to='plants/hero/'),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='plants/thumb/'),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='moisture_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='moisture_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='recommended_pot_materials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='recommended_soil_mixes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='repot_interval_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='repot_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='water_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdefinition',
            name='water_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plantdefinition',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='PlantTraitDefinitionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=10)),
                ('label', models.CharField(max_length=160)),
                ('help_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='plant_definitions.planttraitdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='PlantDefinitionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=10)),
                ('common_name', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='plant_definitions.plantdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='PlantDefinitionTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_traits', to='plant_definitions.plantdefinition')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_values', to='plant_definitions.planttraitdefinition')),
            ],
        ),
        migrations.AddIndex(
            model_name='planttraitdefinitiontranslation',
            index=models.Index(fields=['language_code'], name='plant_defin_languag_05b977_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planttraitdefinitiontranslation',
            unique_together={('trait', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='plantdefinitiontranslation',
            index=models.Index(fields=['language_code'], name='plant_defin_languag_f5806a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantdefinitiontranslation',
            unique_together={('plant_definition', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='plantdefinitiontrait',
            index=models.Index(fields=['plant_definition'], name='plant_defin_plant_d_3f7e72_idx'),
        ),
        migrations.AddIndex(
            model_name='plantdefinitiontrait',
            index=models.Index(fields=['trait'], name='plant_defin_trait_i_6bbe19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantdefinitiontrait',
            unique_together={('plant_definition', 'trait')},
        ),
    ]
