# Generated by Django 4.2 on 2025-12-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_definitions', '0002_planttraitdefinition_alter_plantdefinition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdefinition',
            name='external_id',
            field=models.SlugField(max_length=160, unique=True),
        ),
    ]
