# Generated by Django 5.2.7 on 2025-10-16 09:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('plant_definitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=160)),
                ('notes', models.TextField(blank=True, default='')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('photo_uri', models.CharField(blank=True, default='', max_length=512)),
                ('light_level', models.CharField(choices=[('bright-direct', 'Bright direct'), ('bright-indirect', 'Bright indirect'), ('medium', 'Medium'), ('low', 'Low'), ('very-low', 'Very low')], default='medium', max_length=20)),
                ('orientation', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West')], default='S', max_length=1)),
                ('distance_cm', models.PositiveIntegerField(default=0)),
                ('pot_material', models.CharField(blank=True, default='', max_length=40)),
                ('soil_mix', models.CharField(blank=True, default='', max_length=40)),
                ('create_auto_tasks', models.BooleanField(default=False)),
                ('water_task_enabled', models.BooleanField(default=False)),
                ('repot_task_enabled', models.BooleanField(default=False)),
                ('moisture_required', models.BooleanField(default=False)),
                ('fertilize_required', models.BooleanField(default=False)),
                ('care_required', models.BooleanField(default=False)),
                ('last_watered', models.CharField(blank=True, default='', max_length=32)),
                ('last_repotted', models.CharField(blank=True, default='', max_length=32)),
                ('moisture_interval_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fertilize_interval_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('care_interval_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('repot_interval_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_instances', to='locations.location')),
                ('plant_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='plant_definitions.plantdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
