# Generated by Django 5.2.7 on 2025-10-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_instances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantinstance',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
