from django.core.management.base import BaseCommand
from plants.models import Plant

# Allowed trait keys your UI knows:
# sun, soil, temp, humidity, difficulty, watering, moisture, toxic

SAMPLES = [
    # ======= POPULAR (10) =======
    dict(
        name="Monstera",
        latin="Monstera deliciosa",
        popular=True, sun="medium", water="medium", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1551970634-747846a548cb?w=400",
        image_hero_url="https://images.unsplash.com/photo-1470058869958-2a77ade41c02?w=1200",
        description="General indoor plant that prefers bright, indirect light and moderate watering.",
        traits=[
            {"key": "sun", "value": "Bright indirect"},
            {"key": "soil", "value": "Well-draining"},
            {"key": "temp", "value": "18–26°C"},
            {"key": "humidity", "value": "Medium-High"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "watering", "value": "Weekly"},
            {"key": "moisture", "value": "Mist sometimes"},
        ],
    ),
    dict(
        name="Snake Plant",
        latin="Sansevieria trifasciata",
        popular=True, sun="low", water="low", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1608178398319-48f814d0750c?w=400",
        image_hero_url="https://images.unsplash.com/photo-1614594821361-1b98b5eb2d4a?w=1200",
        description="Very tolerant plant: low light and infrequent watering.",
        traits=[
            {"key": "sun", "value": "Low-Medium"},
            {"key": "soil", "value": "Fast draining"},
            {"key": "watering", "value": "Every 2–3 weeks"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "16–27°C"},
            {"key": "humidity", "value": "Low-Medium"},
        ],
    ),
    dict(
        name="ZZ Plant",
        latin="Zamioculcas zamiifolia",
        popular=True, sun="low", water="low", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1598899134739-24b5c2f2a1b9?w=400",
        image_hero_url="https://images.unsplash.com/photo-1611222616243-2b8b32f2f1c6?w=1200",
        description="Handles low light and drought very well; slow grower.",
        traits=[
            {"key": "sun", "value": "Low-Medium"},
            {"key": "soil", "value": "Gritty mix"},
            {"key": "watering", "value": "Every 2–3 weeks"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–29°C"},
            {"key": "humidity", "value": "Low-Medium"},
        ],
    ),
    dict(
        name="Pothos",
        latin="Epipremnum aureum",
        popular=True, sun="low", water="medium", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1617093727343-374b9d0f33e3?w=400",
        image_hero_url="https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200",
        description="Forgiving vine that thrives in many conditions; great beginner plant.",
        traits=[
            {"key": "sun", "value": "Low-Bright indirect"},
            {"key": "soil", "value": "Airy mix"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–29°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Rubber Plant",
        latin="Ficus elastica",
        popular=True, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1601412436009-d964bd89a5e3?w=400",
        image_hero_url="https://images.unsplash.com/photo-1525013066836-c6090f0ad9a5?w=1200",
        description="Upright ficus that prefers bright light and steady care.",
        traits=[
            {"key": "sun", "value": "Bright indirect"},
            {"key": "soil", "value": "Chunky mix"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium"},
            {"key": "toxic", "value": "Irritating sap"},
        ],
    ),
    dict(
        name="Peace Lily",
        latin="Spathiphyllum wallisii",
        popular=True, sun="low", water="high", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1614594821361-1b98b5eb2d4a?w=400",
        image_hero_url="https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200",
        description="Classic indoor bloomer; prefers evenly moist soil and low–medium light.",
        traits=[
            {"key": "sun", "value": "Low-Medium"},
            {"key": "soil", "value": "Moist mix"},
            {"key": "watering", "value": "Keep moist"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium-High"},
            {"key": "toxic", "value": "Toxic"},
        ],
    ),
    dict(
        name="Spider Plant",
        latin="Chlorophytum comosum",
        popular=True, sun="medium", water="medium", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=400",
        image_hero_url="https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=1200",
        description="Easy arching plant that produces baby plantlets; adaptable.",
        traits=[
            {"key": "sun", "value": "Medium indirect"},
            {"key": "soil", "value": "All-purpose"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "16–27°C"},
            {"key": "humidity", "value": "Medium"},
            {"key": "toxic", "value": "Non-toxic"},
        ],
    ),
    dict(
        name="Aloe Vera",
        latin="Aloe vera",
        popular=True, sun="high", water="low", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1589739900266-43b89b3e2c88?w=400",
        image_hero_url="https://images.unsplash.com/photo-1524592714635-d77511a4834d?w=1200",
        description="Succulent that loves sun and sparse watering.",
        traits=[
            {"key": "sun", "value": "Bright direct"},
            {"key": "soil", "value": "Cactus mix"},
            {"key": "watering", "value": "Every 2–4 weeks"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–29°C"},
            {"key": "humidity", "value": "Low"},
        ],
    ),
    dict(
        name="Fiddle Leaf Fig",
        latin="Ficus lyrata",
        popular=True, sun="high", water="medium", difficulty="hard",
        image_thumb_url="https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400",
        image_hero_url="https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200",
        description="Statement ficus demanding bright light and consistent care.",
        traits=[
            {"key": "sun", "value": "Bright indirect"},
            {"key": "soil", "value": "Aroid mix"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Hard"},
            {"key": "temp", "value": "20–27°C"},
            {"key": "humidity", "value": "Medium-High"},
            {"key": "toxic", "value": "Irritating sap"},
        ],
    ),
    dict(
        name="Philodendron Heartleaf",
        latin="Philodendron hederaceum",
        popular=True, sun="medium", water="medium", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1518834107812-67b2a5f0f7fb?w=400",
        image_hero_url="https://images.unsplash.com/photo-1509389928833-3c55bbf9a3f1?w=1200",
        description="Trailing philodendron with heart-shaped leaves; easy and forgiving.",
        traits=[
            {"key": "sun", "value": "Medium indirect"},
            {"key": "soil", "value": "Aroid mix"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),

    # ======= 20 MORE (not popular by default) =======
    dict(
        name="Dracaena",
        latin="Dracaena fragrans",
        popular=False, sun="medium", water="medium", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1614597341694-bd2b55a0b0b9?w=400",
        image_hero_url="https://images.unsplash.com/photo-1516397281156-ca07cf9746fc?w=1200",
        description="Columnar plant tolerant of indoor conditions.",
        traits=[
            {"key": "sun", "value": "Medium"},
            {"key": "soil", "value": "Free-draining"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Orchid",
        latin="Phalaenopsis",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1533038590840-1cde6e668a91?w=400",
        image_hero_url="https://images.unsplash.com/photo-1436891620584-47fd0e565afb?w=1200",
        description="Moth orchid; blooms in moderate light and consistent moisture.",
        traits=[
            {"key": "sun", "value": "Medium"},
            {"key": "soil", "value": "Bark mix"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–26°C"},
            {"key": "humidity", "value": "Medium-High"},
        ],
    ),
    dict(
        name="Calathea",
        latin="Calathea roseopicta",
        popular=False, sun="low", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1518732714860-b62714ce0b18?w=400",
        image_hero_url="https://images.unsplash.com/photo-1498855926480-d98e83099315?w=1200",
        description="Prayer-type plant with patterned leaves; enjoys humidity.",
        traits=[
            {"key": "sun", "value": "Low-Medium"},
            {"key": "soil", "value": "Rich airy"},
            {"key": "watering", "value": "Lightly moist"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–26°C"},
            {"key": "humidity", "value": "High"},
        ],
    ),
    dict(
        name="Chinese Evergreen",
        latin="Aglaonema commutatum",
        popular=False, sun="low", water="medium", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1591076482161-dc3c18b6a3e5?w=400",
        image_hero_url="https://images.unsplash.com/photo-1524592714635-d77511a4834d?w=1200",
        description="Great low-light plant with colorful foliage.",
        traits=[
            {"key": "sun", "value": "Low-Medium"},
            {"key": "soil", "value": "Airy mix"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Dieffenbachia",
        latin="Dieffenbachia seguine",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1520880867055-1e30d1cb001c?w=400",
        image_hero_url="https://images.unsplash.com/photo-1533038590840-1cde6e668a91?w=1200",
        description="Variegated cane plant; brightens corners with patterned leaves.",
        traits=[
            {"key": "sun", "value": "Medium"},
            {"key": "soil", "value": "Well-draining"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium"},
            {"key": "toxic", "value": "Toxic"},
        ],
    ),
    dict(
        name="Prayer Plant",
        latin="Maranta leuconeura",
        popular=False, sun="low", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1518562923427-19e694fbd8e9?w=400",
        image_hero_url="https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200",
        description="Folds leaves at night; loves humidity and soft light.",
        traits=[
            {"key": "sun", "value": "Low-Medium"},
            {"key": "soil", "value": "Rich airy"},
            {"key": "watering", "value": "Slightly moist"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–26°C"},
            {"key": "humidity", "value": "High"},
        ],
    ),
    dict(
        name="Umbrella Plant",
        latin="Schefflera arboricola",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=400",
        image_hero_url="https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200",
        description="Shrubby indoor tree with radiating leaflets.",
        traits=[
            {"key": "sun", "value": "Medium-Bright"},
            {"key": "soil", "value": "Well-draining"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium"},
            {"key": "toxic", "value": "Mildly toxic"},
        ],
    ),
    dict(
        name="Boston Fern",
        latin="Nephrolepis exaltata",
        popular=False, sun="low", water="high", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1493414334508-44c6479a8b22?w=400",
        image_hero_url="https://images.unsplash.com/photo-1516919549054-6b4b27c63a2f?w=1200",
        description="Classic fern that thrives in humidity and consistently moist soil.",
        traits=[
            {"key": "sun", "value": "Low-Medium"},
            {"key": "soil", "value": "Moist mix"},
            {"key": "watering", "value": "Keep moist"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "16–24°C"},
            {"key": "humidity", "value": "High"},
        ],
    ),
    dict(
        name="English Ivy",
        latin="Hedera helix",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400",
        image_hero_url="https://images.unsplash.com/photo-1499696010180-025ef6e1a8f8?w=1200",
        description="Trailing/climbing vine that appreciates cooler rooms.",
        traits=[
            {"key": "sun", "value": "Medium"},
            {"key": "soil", "value": "Free-draining"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "12–21°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Jade Plant",
        latin="Crassula ovata",
        popular=False, sun="high", water="low", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400",
        image_hero_url="https://images.unsplash.com/photo-1545249390-95b1430b0893?w=1200",
        description="Succulent tree with thick leaves; prefers bright light.",
        traits=[
            {"key": "sun", "value": "Bright direct"},
            {"key": "soil", "value": "Cactus mix"},
            {"key": "watering", "value": "Every 2–4 weeks"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Low"},
        ],
    ),
    dict(
        name="Areca Palm",
        latin="Dypsis lutescens",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1528920304568-7aa6cace6840?w=400",
        image_hero_url="https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200",
        description="Feathery palm that likes bright, filtered light and steady moisture.",
        traits=[
            {"key": "sun", "value": "Medium-Bright"},
            {"key": "soil", "value": "Perlite mix"},
            {"key": "watering", "value": "Slightly moist"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium-High"},
        ],
    ),
    dict(
        name="Kentia Palm",
        latin="Howea forsteriana",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1493673272479-7f58f2a89d89?w=400",
        image_hero_url="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200",
        description="Elegant slow-growing palm; tolerates lower light than most palms.",
        traits=[
            {"key": "sun", "value": "Medium"},
            {"key": "soil", "value": "Rich, free-draining"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "16–26°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Bird of Paradise",
        latin="Strelitzia nicolai",
        popular=False, sun="high", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1543322748-33df6d3db806?w=400",
        image_hero_url="https://images.unsplash.com/photo-1483794344563-d27a8d18014e?w=1200",
        description="Large tropical with upright leaves; craves bright light.",
        traits=[
            {"key": "sun", "value": "Bright light"},
            {"key": "soil", "value": "Chunky mix"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–29°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Peperomia",
        latin="Peperomia obtusifolia",
        popular=False, sun="medium", water="low", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=400",
        image_hero_url="https://images.unsplash.com/photo-1516397281156-ca07cf9746fc?w=1200",
        description="Compact semi-succulent that prefers bright, indirect light.",
        traits=[
            {"key": "sun", "value": "Medium-Bright"},
            {"key": "soil", "value": "Free-draining"},
            {"key": "watering", "value": "When dry"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Low-Medium"},
        ],
    ),
    dict(
        name="Hoya",
        latin="Hoya carnosa",
        popular=False, sun="medium", water="low", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1523755231516-e43fd2e8dca5?w=400",
        image_hero_url="https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=1200",
        description="Wax plant with fragrant clusters; loves bright, indirect light.",
        traits=[
            {"key": "sun", "value": "Bright indirect"},
            {"key": "soil", "value": "Chunky mix"},
            {"key": "watering", "value": "When half dry"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–29°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Anthurium",
        latin="Anthurium andraeanum",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1524592714635-d77511a4834d?w=400",
        image_hero_url="https://images.unsplash.com/photo-1465101162946-4377e57745c3?w=1200",
        description="Glossy leaves and colorful spathes; prefers warmth and humidity.",
        traits=[
            {"key": "sun", "value": "Medium-Bright"},
            {"key": "soil", "value": "Aroid mix"},
            {"key": "watering", "value": "Slightly moist"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "High"},
            {"key": "toxic", "value": "Toxic"},
        ],
    ),
    dict(
        name="Croton",
        latin="Codiaeum variegatum",
        popular=False, sun="high", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1504194104404-433180773017?w=400",
        image_hero_url="https://images.unsplash.com/photo-1523755231516-e43fd2e8dca5?w=1200",
        description="Colorful foliage that wants strong light and steady moisture.",
        traits=[
            {"key": "sun", "value": "Bright light"},
            {"key": "soil", "value": "Well-draining"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "20–29°C"},
            {"key": "humidity", "value": "Medium-High"},
            {"key": "toxic", "value": "Toxic"},
        ],
    ),
    dict(
        name="Cast Iron Plant",
        latin="Aspidistra elatior",
        popular=False, sun="low", water="low", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1461151304267-38535e780c79?w=400",
        image_hero_url="https://images.unsplash.com/photo-1516919549054-6b4b27c63a2f?w=1200",
        description="Nearly indestructible; handles low light and irregular care.",
        traits=[
            {"key": "sun", "value": "Low-Medium"},
            {"key": "soil", "value": "Free-draining"},
            {"key": "watering", "value": "Every 2–3 weeks"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "10–24°C"},
            {"key": "humidity", "value": "Low-Medium"},
        ],
    ),
    dict(
        name="Ponytail Palm",
        latin="Beaucarnea recurvata",
        popular=False, sun="high", water="low", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=400",
        image_hero_url="https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=1200",
        description="Caudex plant that stores water; loves sun and dry spells.",
        traits=[
            {"key": "sun", "value": "Bright direct"},
            {"key": "soil", "value": "Cactus mix"},
            {"key": "watering", "value": "Every 3–4 weeks"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–29°C"},
            {"key": "humidity", "value": "Low"},
        ],
    ),
    dict(
        name="Norfolk Island Pine",
        latin="Araucaria heterophylla",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400",
        image_hero_url="https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200",
        description="Indoor conifer; prefers bright, cool rooms and even moisture.",
        traits=[
            {"key": "sun", "value": "Medium-Bright"},
            {"key": "soil", "value": "Perlite mix"},
            {"key": "watering", "value": "Evenly moist"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "10–21°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Golden Barrel Cactus",
        latin="Echinocactus grusonii",
        popular=False, sun="high", water="low", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=400",
        image_hero_url="https://images.unsplash.com/photo-1524592714635-d77511a4834d?w=1200",
        description="Sun-loving cactus; requires sharp drainage and rare watering.",
        traits=[
            {"key": "sun", "value": "Full sun"},
            {"key": "soil", "value": "Cactus mix"},
            {"key": "watering", "value": "Monthly"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–32°C"},
            {"key": "humidity", "value": "Low"},
        ],
    ),
    dict(
        name="String of Pearls",
        latin="Senecio rowleyanus",
        popular=False, sun="high", water="low", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1518834107812-67b2a5f0f7fb?w=400",
        image_hero_url="https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200",
        description="Trailing succulent beads; likes strong light and careful watering.",
        traits=[
            {"key": "sun", "value": "Bright light"},
            {"key": "soil", "value": "Cactus mix"},
            {"key": "watering", "value": "Infrequent"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Low"},
        ],
    ),
    dict(
        name="Parlor Palm",
        latin="Chamaedorea elegans",
        popular=False, sun="low", water="medium", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1493414334508-44c6479a8b22?w=400",
        image_hero_url="https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200",
        description="Compact palm that tolerates low light and typical indoor humidity.",
        traits=[
            {"key": "sun", "value": "Low-Medium"},
            {"key": "soil", "value": "All-purpose"},
            {"key": "watering", "value": "Slightly moist"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–26°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Rubber Tree Burgundy",
        latin="Ficus elastica 'Burgundy'",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=400",
        image_hero_url="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200",
        description="Dark-leaf rubber plant variant; likes bright, filtered light.",
        traits=[
            {"key": "sun", "value": "Bright indirect"},
            {"key": "soil", "value": "Chunky mix"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Pilea (Chinese Money Plant)",
        latin="Pilea peperomioides",
        popular=False, sun="medium", water="medium", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1518732714860-b62714ce0b18?w=400",
        image_hero_url="https://images.unsplash.com/photo-1499696010180-025ef6e1a8f8?w=1200",
        description="Round leaves; likes bright, indirect light and even moisture.",
        traits=[
            {"key": "sun", "value": "Medium-Bright"},
            {"key": "soil", "value": "Well-draining"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–26°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Swiss Cheese Vine",
        latin="Monstera adansonii",
        popular=False, sun="medium", water="medium", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1518834107812-67b2a5f0f7fb?w=400",
        image_hero_url="https://images.unsplash.com/photo-1509389928833-3c55bbf9a3f1?w=1200",
        description="Fenestrated vining Monstera; climbs with support.",
        traits=[
            {"key": "sun", "value": "Medium indirect"},
            {"key": "soil", "value": "Aroid mix"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium-High"},
        ],
    ),
    dict(
        name="Rubber Plant Tineke",
        latin="Ficus elastica 'Tineke'",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1601412436009-d964bd89a5e3?w=400",
        image_hero_url="https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=1200",
        description="Variegated rubber plant needing bright, indirect light.",
        traits=[
            {"key": "sun", "value": "Bright indirect"},
            {"key": "soil", "value": "Chunky mix"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Agave",
        latin="Agave attenuata",
        popular=False, sun="high", water="low", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=400",
        image_hero_url="https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200",
        description="Architectural rosette; craves sun and minimal water.",
        traits=[
            {"key": "sun", "value": "Full sun"},
            {"key": "soil", "value": "Gritty mix"},
            {"key": "watering", "value": "Infrequent"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–32°C"},
            {"key": "humidity", "value": "Low"},
        ],
    ),
    dict(
        name="Oxalis Triangularis",
        latin="Oxalis triangularis",
        popular=False, sun="medium", water="medium", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=400",
        image_hero_url="https://images.unsplash.com/photo-1498855926480-d98e83099315?w=1200",
        description="Purple shamrock; opens by day, closes at night.",
        traits=[
            {"key": "sun", "value": "Medium"},
            {"key": "soil", "value": "Well-draining"},
            {"key": "watering", "value": "Lightly moist"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "15–24°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Chinese Evergreen Red",
        latin="Aglaonema 'Red Siam'",
        popular=False, sun="low", water="medium", difficulty="easy",
        image_thumb_url="https://images.unsplash.com/photo-1518732714860-b62714ce0b18?w=400",
        image_hero_url="https://images.unsplash.com/photo-1493414334508-44c6479a8b22?w=1200",
        description="Colorful Aglaonema cultivar for lower light spots.",
        traits=[
            {"key": "sun", "value": "Low-Medium"},
            {"key": "soil", "value": "Airy mix"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Easy"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Parthenocissus (Cissus)",
        latin="Cissus rhombifolia",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1504194104404-433180773017?w=400",
        image_hero_url="https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=1200",
        description="Grape ivy; trailing/climbing with glossy leaflets.",
        traits=[
            {"key": "sun", "value": "Medium"},
            {"key": "soil", "value": "Free-draining"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "16–26°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
    dict(
        name="Schefflera Amate",
        latin="Schefflera actinophylla 'Amate'",
        popular=False, sun="medium", water="medium", difficulty="medium",
        image_thumb_url="https://images.unsplash.com/photo-1509389928833-3c55bbf9a3f1?w=400",
        image_hero_url="https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200",
        description="Large glossy leaflets; thrives in bright, filtered light.",
        traits=[
            {"key": "sun", "value": "Medium-Bright"},
            {"key": "soil", "value": "Well-draining"},
            {"key": "watering", "value": "Weekly"},
            {"key": "difficulty", "value": "Medium"},
            {"key": "temp", "value": "18–27°C"},
            {"key": "humidity", "value": "Medium"},
        ],
    ),
]

class Command(BaseCommand):
    help = "Seed ~30 popular houseplants with concise traits (idempotent)."

    def handle(self, *args, **opts):
        created_cnt = 0
        updated_cnt = 0
        for p in SAMPLES:
            obj, created = Plant.objects.update_or_create(
                latin=p["latin"],  # stable key for updates
                defaults=p,
            )
            created_cnt += int(created)
            updated_cnt += int(not created)
            self.stdout.write(self.style.SUCCESS(f"{'Created' if created else 'Updated'}: {obj.name}"))
        self.stdout.write(self.style.NOTICE(f"Done. Created: {created_cnt}, Updated: {updated_cnt}"))
