# Generated by Django 5.2.7 on 2025-10-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.CharField(choices=[('water', 'Watering'), ('moisture', 'Misting'), ('fertilize', 'Fertilising'), ('care', 'General care'), ('repot', 'Repotting')], max_length=16),
        ),
    ]
