# Generated by Django 5.2.7 on 2025-11-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindertask',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
