# Generated by Django 5.2.8 on 2025-11-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_populate_profile_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='tile_motive',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Tile gloom style: light or dark.', max_length=5),
        ),
    ]
