# Generated by Django 6.0.1 on 2026-01-22 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profilesettings_tile_motive'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenotifications',
            name='email_minute',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='profilenotifications',
            name='push_minute',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='profilenotifications',
            name='timezone',
            field=models.CharField(default='Europe/Warsaw', max_length=64),
        ),
    ]
