# Generated by Django 6.0.1 on 2026-01-22 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profilenotifications_email_minute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push')], max_length=16)),
                ('local_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_delivery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['local_date', 'channel'], name='profiles_no_local_d_bfedf5_idx'), models.Index(fields=['user', 'local_date'], name='profiles_no_user_id_c33d65_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'channel', 'local_date'), name='uniq_delivery_user_channel_date')],
            },
        ),
    ]
