# Generated by Django 6.0.1 on 2026-01-22 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_notificationdeliverylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationdeliverylog',
            name='uniq_delivery_user_channel_date',
        ),
        migrations.AddField(
            model_name='notificationdeliverylog',
            name='kind',
            field=models.CharField(choices=[('due_today', 'Due today'), ('overdue_1d', 'Overdue 1 day')], default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['user', 'channel', 'kind', 'local_date'], name='profiles_no_user_id_d90ac3_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdeliverylog',
            constraint=models.UniqueConstraint(fields=('user', 'channel', 'kind', 'local_date'), name='uniq_delivery_user_channel_kind_date'),
        ),
    ]
