# Generated by Django 6.0.1 on 2026-01-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_notificationdeliverylog_uniq_delivery_user_channel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdeliverylog',
            name='kind',
            field=models.CharField(choices=[('due_today', 'Due today'), ('overdue_1d', 'Overdue 1 day')], default='due_today', max_length=32),
        ),
    ]
