# Generated by Django 6.0.1 on 2026-01-26 22:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_pushdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contact', 'Contact'), ('bug', 'Bug report')], max_length=16)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('copy_to_user', models.BooleanField(default=True)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('app_version', models.CharField(blank=True, default='', max_length=64)),
                ('platform', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
